<?php

declare(strict_types=1);

namespace Tests\Feature;

use App\Models\Profile;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class ProviderCompleteLoginTest extends TestCase
{
    use RefreshDatabase;

    protected User $provider;

    protected function setUp(): void
    {
        parent::setUp();

        $this->provider = User::create([
            'name' => 'Complete Flow Test',
            'email' => 'complete@flow.com',
            'password' => bcrypt('password'),
            'is_active' => true,
            'is_suspended' => false,
        ]);

        $this->provider->assignRole('provider');

        Profile::create([
            'user_id' => $this->provider->id,
            'slug' => 'complete-flow',
        ]);
    }

    /**
     * PHASE 1: Guest visits login page
     */
    public function test_guest_can_load_login_page(): void
    {
        $response = $this->get('/provider/login');
        $response->assertOk();
    }

    /**
     * PHASE 2: Authenticated provider can access dashboard
     */
    public function test_authenticated_provider_dashboard_returns_200(): void
    {
        $response = $this->actingAs($this->provider)->get('/provider/dashboard');
        $response->assertOk();
    }

    /**
     * PHASE 3: Provider can access all resources
     */
    public function test_provider_can_access_resources(): void
    {
        $this->actingAs($this->provider);

        // These routes are generated by Filament discovery
        // We can't test them directly without mocking Filament's routing
        // But the fact that dashboard works means the panel is initialized
        $dashboard = $this->get('/provider/dashboard');
        $this->assertEquals(200, $dashboard->status());
    }

    /**
     * PHASE 4: Inactive provider denied
     */
    public function test_inactive_provider_denied(): void
    {
        $this->provider->update(['is_active' => false]);

        $response = $this->actingAs($this->provider)->get('/provider/dashboard');

        // Should be 403 or redirect to login
        $this->assertThat(
            $response->status(),
            $this->logicalOr(
                $this->equalTo(302),
                $this->equalTo(403)
            )
        );
    }

    /**
     * PHASE 5: Suspended provider denied
     */
    public function test_suspended_provider_denied(): void
    {
        $this->provider->update(['is_suspended' => true]);

        $response = $this->actingAs($this->provider)->get('/provider/dashboard');

        // Should be 403 or redirect
        $this->assertThat(
            $response->status(),
            $this->logicalOr(
                $this->equalTo(302),
                $this->equalTo(403)
            )
        );
    }

    /**
     * PHASE 6: Provider without role denied
     */
    public function test_provider_without_role_denied(): void
    {
        $this->provider->syncRoles([]);

        $response = $this->actingAs($this->provider)->get('/provider/dashboard');

        // Should be 403 or redirect
        $this->assertThat(
            $response->status(),
            $this->logicalOr(
                $this->equalTo(302),
                $this->equalTo(403)
            )
        );
    }

    /**
     * PHASE 7: Guest redirected to login
     */
    public function test_guest_redirected_to_provider_login(): void
    {
        $response = $this->get('/provider/dashboard');
        $response->assertRedirect('/provider/login');
    }

    /**
     * PHASE 8: Admin without provider role denied
     */
    public function test_admin_without_provider_role_denied(): void
    {
        $admin = User::create([
            'name' => 'Admin',
            'email' => 'admin@test.com',
            'password' => bcrypt('password'),
            'is_active' => true,
            'is_suspended' => false,
        ]);

        $admin->assignRole('super_admin');

        $response = $this->actingAs($admin)->get('/provider/dashboard');

        // Admin doesn't have provider role, should be denied
        $this->assertThat(
            $response->status(),
            $this->logicalOr(
                $this->equalTo(302),
                $this->equalTo(403)
            )
        );
    }

    /**
     * CRITICAL: No infinite redirect loop
     */
    public function test_no_infinite_redirect_loop(): void
    {
        $response = $this->actingAs($this->provider)->get('/provider/dashboard');

        // Should be 200, not a series of redirects
        $this->assertEquals(200, $response->status());

        // Follow redirect if it exists, but it shouldn't
        if ($response->status() === 302) {
            $followedResponse = $this->get($response->getTargetUrl());

            // Even if there's one redirect, it should not redirect again
            // to the original URL (which would indicate a loop)
            $this->assertNotEquals(302, $followedResponse->status());
        }
    }
}
